title: /home/htorquato
description: Assortment of random things I work on
markdown: kramdown

# for atom feed
author:
  name: Henrique Torquato

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-target-blank

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /post/:year/:month/:day/:title/

exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
